### ISSUE TITLE
Chrome reloads all css files in head

### ISSUE THREAD

**Issue by Requilence** [jQueryKeyframes/jQuery.Keyframes#41]
Looks like after adding new style element to head, Chrome(tested 41) forcing reload of all CSS files (also ignoring all cache, so all files are fully reloaded from remote).
![screen shot 2015-04-16 at 16 18 37](https://cloud.githubusercontent.com/assets/1025231/7180613/4464a948-e454-11e4-9b95-c49e66e575fd.png)

**Comment by krazyjakee** [comment]
I can't recreate this. Could provide a jsfiddle or example?

In your developer tools, have you disabled caching?

**Comment by jmanos** [comment]
This is still an issue and is caused by the StyleFix plugin which is only included in Keyframe's min.js file (so the issue is not present in the normal js file).

Basically, the StyleFix plugin is looping through all elements and performing certain actions on them including reloading all link tags with rel='stylesheet'.

Keyframes seems to run fine without StyleFix, so why is it even included in the min.js file?
